 
import { WidegtsGrid } from "@/src/components/dashboard/WidegtsGrid";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
}

export default function MainPage() {
  return (
    <div className="text-black p-2">
      <h1 className="mt-2 text-3xl">Hello Dashboard</h1>
      <span className="text-xl">Información general</span>

      <WidegtsGrid/>
    </div>
  );
}